name: Build Linux

on:
  push:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ----------- DOWNLOAD GODOT -----------
      - name: Download Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          unzip Godot_v4.2.2-stable_linux.x86_64.zip
          mv Godot_v4.2.2-stable_linux.x86_64 godot
          chmod +x godot

      # -------- EXPORT TEMPLATES ------------
      - name: Install export templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          unzip Godot_v4.2.2-stable_export_templates.tpz
          mv templates/* ~/.local/share/godot/export_templates/4.2.2.stable/

      # -------------- BUILD -----------------
      - name: Export Linux build
        run: |
          mkdir -p build/linux
          ./godot --headless --path . --export-release "Linux/X11" build/linux/SimpleGame.x86_64

      # ------------ ARTIFACT ----------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleGame-Linux
          path: build/linux/